services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
    ports:
      - "8081:80"
      - "8082:8080"
    volumes:
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - etolv-network

  acc-app:
    build: ./acc-frontend
    networks:
      - etolv-network

  portal-app:
    build: ./portal-frontend
    networks:
      - etolv-network

  admin-app:
    build: ./admin-frontend
    networks:
      - etolv-network

  backend-app:
    build: ./backend
    networks:
      - etolv-network

networks:
  etolv-network:
    driver: bridge